# Generated by Django 3.2 on 2021-04-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210419_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Book2',
        ),
    ]
