# Generated by Django 3.2 on 2021-04-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_book_book2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book2',
            new_name='Book',
        ),
    ]
