# Generated by Django 3.2 on 2021-04-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Uni_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(help_text='공지사항 이름', max_length=100)),
                ('post_content', models.TextField(help_text='공지사항 내용')),
                ('post_url', models.URLField()),
                ('attachment_url', models.URLField()),
                ('tag', models.ManyToManyField(to='notice.Tag')),
            ],
        ),
    ]
