# Generated by Django 3.2 on 2021-05-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uni_post',
            old_name='tag',
            new_name='tags',
        ),
    ]
