# Generated by Django 3.2 on 2021-05-09 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_rename_tag_uni_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uni_post',
            old_name='post_content',
            new_name='post_contents',
        ),
    ]
