# Generated by Django 3.2.2 on 2021-05-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_rename_post_content_uni_post_post_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='uni_post',
            name='post_author',
            field=models.CharField(default=str, help_text='공지사항 작성자', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uni_post',
            name='post_date',
            field=models.CharField(default=str, help_text='공지사항 등록일', max_length=50),
            preserve_default=False,
        ),
    ]
