# Generated by Django 3.2 on 2021-04-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-board_name']},
        ),
        migrations.AlterField(
            model_name='board',
            name='board_name',
            field=models.CharField(help_text='Enter your board_name', max_length=100),
        ),
    ]
